using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Xml;

namespace DragonSwordWorldRadar.Installer
{
    public static class TreasureLuaGenerator
    {
        public static int Generate(
            string xmlPath,
            string outputPath)
        {
            XmlDocument document = new XmlDocument
            {
                XmlResolver = null
            };
            document.Load(xmlPath);
            XmlNodeList nodes = document.SelectNodes(
                "//*[local-name()='SectionActorData']");
            if (nodes == null || nodes.Count < 1000)
            {
                throw new InvalidDataException(
                    "The extracted treasure data is incomplete.");
            }

            // Extended metadata is generated locally from the user's game files.
            // PosZ supports height diagnostics, while UIDName identifies the
            // acquisition type without shipping extracted game data in releases.
            List<string> lines = new List<string>
            {
                "-- Generated locally by DragonSwordWorldRadar.",
                "-- Do not edit this file manually; use data/treasure_overrides.txt instead.",
                "return {"
            };
            foreach (XmlNode node in nodes)
            {
                XmlElement element = node as XmlElement;
                if (element == null)
                {
                    continue;
                }

                string cid = GetRequiredValue(element, "CID");
                string section = GetRequiredValue(
                    element,
                    "SectionUID");
                string x = GetRequiredValue(element, "PosX");
                string y = GetRequiredValue(element, "PosY");
                string z = GetOptionalValue(element, "PosZ");
                string uidName = GetOptionalValue(
                    element,
                    "UIDName") ?? String.Empty;
                string groupId = GetOptionalValue(
                    element,
                    "GroupID");

                ValidateInteger(cid, "CID");
                ValidateInteger(section, "SectionUID");
                ValidateNumber(x, "PosX");
                ValidateNumber(y, "PosY");
                if (!String.IsNullOrWhiteSpace(z))
                {
                    ValidateNumber(z, "PosZ");
                }
                if (!String.IsNullOrWhiteSpace(groupId))
                {
                    ValidateInteger(groupId, "GroupID");
                }

                StringBuilder line = new StringBuilder();
                line.Append("    { save_id = ");
                line.Append(cid);
                line.Append(", section = \"");
                line.Append(EscapeLuaString(section));
                line.Append("\", x = ");
                line.Append(x);
                line.Append(", y = ");
                line.Append(y);
                if (!String.IsNullOrWhiteSpace(z))
                {
                    line.Append(", z = ");
                    line.Append(z);
                }
                line.Append(", uid_name = \"");
                line.Append(EscapeLuaString(uidName));
                line.Append("\", group_id = ");
                line.Append(String.IsNullOrWhiteSpace(groupId)
                    ? "0"
                    : groupId.Trim());
                line.Append(" },");
                lines.Add(line.ToString());
            }
            lines.Add("}");

            File.WriteAllLines(
                outputPath,
                lines,
                new UTF8Encoding(false));
            return nodes.Count;
        }

        private static string EscapeLuaString(string value)
        {
            return (value ?? String.Empty)
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n");
        }

        private static string GetRequiredValue(
            XmlElement element,
            string localName)
        {
            string value = GetOptionalValue(element, localName);
            if (value != null)
            {
                return value;
            }

            throw new InvalidDataException(
                "The extracted treasure data is missing field '" +
                localName +
                "'.");
        }

        private static string GetOptionalValue(
            XmlElement element,
            string localName)
        {
            foreach (XmlAttribute attribute in element.Attributes)
            {
                if (string.Equals(
                    attribute.LocalName,
                    localName,
                    StringComparison.OrdinalIgnoreCase))
                {
                    return attribute.Value;
                }
            }

            return FindDescendantValue(element, localName);
        }

        private static string FindDescendantValue(
            XmlNode node,
            string localName)
        {
            foreach (XmlNode child in node.ChildNodes)
            {
                XmlElement element = child as XmlElement;
                if (element == null)
                {
                    continue;
                }

                if (string.Equals(
                    element.LocalName,
                    localName,
                    StringComparison.OrdinalIgnoreCase)
                    && !String.IsNullOrWhiteSpace(element.InnerText))
                {
                    return element.InnerText.Trim();
                }

                string nested = FindDescendantValue(element, localName);
                if (nested != null)
                {
                    return nested;
                }
            }

            return null;
        }

        private static void ValidateInteger(
            string value,
            string fieldName)
        {
            ulong ignored;
            if (!ulong.TryParse(
                value,
                NumberStyles.None,
                CultureInfo.InvariantCulture,
                out ignored))
            {
                throw new InvalidDataException(
                    fieldName + " contains an invalid value.");
            }
        }

        private static void ValidateNumber(
            string value,
            string fieldName)
        {
            double parsed;
            if (!double.TryParse(
                    value,
                    NumberStyles.Float,
                    CultureInfo.InvariantCulture,
                    out parsed)
                || double.IsNaN(parsed)
                || double.IsInfinity(parsed))
            {
                throw new InvalidDataException(
                    fieldName + " contains an invalid value.");
            }
        }
    }
}
